server:
  port: 8081

spring:
  application:
    name: post-query-service

  datasource:
    url: jdbc:postgresql://localhost:5433/comeandcommue?currentSchema=community
    username: anan
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: io.comeandcommue.post_query_service
